spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

redisson:
  config: |
    singleServerConfig:
      address: "redis://127.0.0.1:6379"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
